import { Pool } from 'pg';
import { config } from './config.js';

export const pool = new Pool({
  host: config.database.host,
  port: config.database.port,
  user: config.database.user,
  password: config.database.password,
  database: config.database.name,
});

export async function initializeDatabase(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar NOT NULL,
      email varchar NOT NULL UNIQUE,
      password varchar NOT NULL
    )
  `);
}
